### ISSUE TITLE
The advanced settings of the Fraud Protection sections is being saved incorrectly

### ISSUE THREAD

**Issue by eduardoumpierre** [Automattic/woocommerce-payments#10393]
### Describe the bug

Currently, the advanced settings are being saved with the "review" outcome, but it should be "block" instead. 

### To Reproduce

Apply the following diff:
```diff
diff --git a/client/settings/fraud-protection/advanced-settings/index.tsx b/client/settings/fraud-protection/advanced-settings/index.tsx
index b39a65970..252b15908 100644
--- a/client/settings/fraud-protection/advanced-settings/index.tsx
+++ b/client/settings/fraud-protection/advanced-settings/index.tsx
@@ -129,6 +129,8 @@ const FraudProtectionAdvancedSettingsPage: React.FC = () => {
 		);
 	}, [ advancedFraudProtectionSettings ] );
 
+	console.log({ protectionSettingsUI });
+
 	useLayoutEffect( () => {
 		const saveButton = document.querySelector(
 			'.fraud-protection-header-save-button'

```

1. Go to **Payments > Fraud protection**
2. Enable the advanced settings and click on "Configure"
3. On the "Advanced fraud protection" page, enable the "Purchase Price Threshold" rule
4. Check the console—the `purchase_price_threshold` key should look like this:
```
purchase_price_threshold: 
  block: false
  enabled: true
  max_amount: null
  min_amount: null
```

### Expected behavior

1. Go to **Payments > Fraud protection**
2. Enable the advanced settings and click on "Configure"
3. On the "Advanced fraud protection" page, enable the "Purchase Price Threshold" rule
4. Check the console—the `purchase_price_threshold` key should look like this:
```
purchase_price_threshold: 
  block: true
  enabled: true
  max_amount: null
  min_amount: null
```
