### ISSUE TITLE
E2E: Avoid server containers conflict

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#1560]
[Reference #539](https://github.com/Automattic/woocommerce-payments/pull/539#issuecomment-659338263)

Is a know problem that the e2e tests setup creates a server containers conflict. Because we are cloning the server and using the same docker-compose.yml config. Forcing us to remove the current server containers or modify by hand the e2e server clone.

### 1. Use environment variables in compose (🤓 elegant one)
Update server `docker-compose.yml` to use env vars with fallback values like:
```yml
container_name: ${COMPOSE_WP_NAME:-woocommerce_payments_server_wordpress}
ports:
  - "${COMPOSE_WP_PORT:-8086}:80"
```
And update `tests/e2e/README.md` to include the new variables to define before running setup.

### 2. Patch compose (🔨 hacky one)
Patch the `docker-compose.yml` file in `tests/e2e/env/setup.sh` after clone using something like:
```sh
perl -i -pe 's/(container_name:.*)/$1_e2e/' docker-compose.yml
perl -i -pe 's/8086/8089/' docker-compose.yml
```
