### ISSUE TITLE
Disputes task dismiss action is cut off

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#4470]
### Describe the bug
I was just testing this again on the Happiness site and noticed something a little off. The Dismiss action (from the ellipses menu on the right of the task) gets cut off when I open it. The text is not readable at all so this is an accessibility problem, and it's not possible to dismiss the task.
![Screen Recording 7-21-2022 at 8 45 PM](https://user-images.githubusercontent.com/5121465/180345688-ef7d402b-499e-4ee1-a438-9a727309f0e8.gif)

I didn't see any closed issues for this so forgive me if it's already been fixed. I know the Happiness site is not fully up to date.

### To Reproduce

1. With at least 1 dispute on your site go to WooCommerce Payments > Overview
2. Click on the ellipses menu to the right of the Disputes task
3. See error

### Expected behavior
The action should appear outside the container of the task list so the full menu and all text is visible.

### Desktop (please complete the following information):

I'm using Firefox on a Mac V12.4
cc @james-allan

**Comment by elizaan36** [comment]
Update: @jbordonado [was not able to reproduce this bug](https://github.com/Automattic/woocommerce-payments/pull/4707#issuecomment-1240679817) but I'm still seeing it on the test site.
https://share.getcloudapp.com/nOubN8QG

**Comment by elizaan36** [comment]
@bradyv is also seeing the bug on his test site.

**Comment by brucealdridge** [comment]
I am unable to replicate.
 - latest version of Chrome
 - dev mode (`SCRIPT_DEBUG`) enabled / disabled.
 - with and without #4707 changes

**Comment by brucealdridge** [comment]
Have managed to see it replicated on a _stagingwebsite_ but unable to find the root cause or replicate locally with a _testsite_. 

_stagingwebsite_ is running latest WP, WC, WCPay
_testsite_ is running latest WP, WC, WCPay (fresh install using wp cli)

Inspecting the page shows differing css for popover component, also additional classes are added on _testsite_

_stagingwebsite_
```css
element.style {
    position: absolute;
    opacity: 1;
    transform: translateY(0em) scale(1) translateZ(0px);
    transform-origin: 100% 0% 0px;
    left: 472px;
    top: 67px;
}
```

_testsite_
```css
element.style {
    top: 630.695px;
    left: 1233px;
}
```
![Screenshot 2022-09-09 at 4 10 12 PM](https://user-images.githubusercontent.com/57298/189270806-6539d048-df7c-40b6-ab08-4ad2172ebd5e.png)
