### ISSUE TITLE
Add email viewer tooling to development environment

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6223]
### Description
We need a way to see emails sent from the WooCommerce store. For example – when testing email related flows, e.g. exporting deposit reports (generated report is emailed). 

[MailHog](https://github.com/mailhog/MailHog) or [MailCatcher](https://mailcatcher.me/) are good options for accessing emails during development, and a relatively simple to set up in docker. 

I propose we implement something like MailHog or MailCatcher in our docker env so we have this facility in our standard env for all to use.

**Comment by haszari** [comment]
Here's a cheat sheet for setting up MailHog.

Add MailHog container to docker-compose & expose the web UI:

```yml
# docker-compose.yml
services:
  # … other services …
  mailhog:
    image: mailhog/mailhog
    ports:
      - 5292:8025 # web ui
```

Use a mu-plugin in WordPress install to configure and enable MailHog:

```yml
# docker-compose.yml
services:
  wordpress:
    # … other config …
    volumes:
      # … other volumes …
        - ./docker/mailhog.php:/var/www/html/wp-content/mu-plugins/mailhog.php
  
```

```php
<?php
// ./docker/mailhog.php

add_action( 'phpmailer_init', function ( $php_mailer ) {
    $php_mailer->Host     = 'mailhog';
    $php_mailer->Port     = 1025;
    $php_mailer->From     = 'wordpress@localhost.test';
    $php_mailer->FromName = 'WordPress';
    $php_mailer->IsSMTP();
}, 10 );

add_filter( 'wp_mail_from', fn( $email ) => 'wordpress@localhost' );

add_filter( 'wp_mail_from_name', fn( $name ) => 'Local WordPress dev' );

```
